---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: gradle:jdk11
    environment:
      BINTRAY_USER:
        from_secret: BINTRAY_USER
      BINTRAY_TOKEN:
        from_secret: BINTRAY_TOKEN
    commands:
      - echo "127.0.0.1 warehouse" >> /etc/hosts
      - echo "127.0.0.1 delivery" >> /etc/hosts
      - gradle clean build -p warehouse --info
      - gradle clean build -p delivery --info