image: gradle:jdk11

stages:
  - build
  - publish

build:
  stage: build
  cache:
    paths:
      - .gradle
  script:
    - gradle clean build

publish:
  stage: publish
  script:
    - gradle :warehouse:bintrayUpload :delivery:bintrayUpload
  only:
    - master